server:
  image: alonsochang/spring_prop
  command: "/bin/bash -c 'cd data-rest && mvn spring-boot:run'"
  working_dir: /app
  volumes:
    - $HOME/.m2:/root/.m2
    - ./:/app
  ports:
   - "8000:8000"
